### ISSUE TITLE
Can't call fixed_price slingshot's buy_nft_certificate()

### ISSUE THREAD

**Issue by justomat** [Origin-Byte/nft-protocol#111]
i tried calling buy_nft_certificate() from a fixed_price slingshot at `0x86c81d52b427a8e6ea6e3fe2cc513e2b1c2211ee`
with the necessary params as shown here

<img width="524" alt="Screenshot 2022-11-30 at 11 47 46" src="https://user-images.githubusercontent.com/5717479/204729375-b1e10fc2-2522-4919-952e-7ff9aa2924a8.png">
<img width="434" alt="Screenshot 2022-11-30 at 11 47 24" src="https://user-images.githubusercontent.com/5717479/204729376-ac2af2f6-6132-4d92-8ac1-5e064c3a9037.png">

but for some reason i was getting this error
```
RPC Error: Could not find the referenced object 0x5283b785eb906160a073748c517a1f556bb6e8e0 at version None.
```
<img width="1183" alt="Screenshot 2022-11-30 at 11 47 56" src="https://user-images.githubusercontent.com/5717479/204729370-66497649-3290-4312-aa65-3d0a46ecc715.png">

which is weird as the address is referring to the wallet address, which obviously exists and could be found. I'm quite lost here does anybody knows if I'm calling the method incorrectly.

**Comment by Suficio** [comment]
Sorry for not getting to you earlier on the issue!
The market interface has changed since a lot this issue was initially filed and we've tested it in production thus I'll close this issue.
