### ISSUE TITLE
Rename `transfer_whitelist` file to `transfer_allowlist`

### ISSUE THREAD

**Issue by bausano** [Origin-Byte/nft-protocol#188]
Ah I forgot to rename this file

_Originally posted by @bausano in https://github.com/Origin-Byte/nft-protocol/pull/186#discussion_r1060025504_

**Comment by nmboavida** [comment]
Solved in commit: https://github.com/Origin-Byte/nft-protocol/pull/186/commits/535b618048c46d74d1bc1301fd3988fdea155a03
