### ISSUE TITLE
Incorrect seller in TradeFilledEvent in the internal call `buy_nft_`

### ISSUE THREAD

**Issue by rm1138** [Origin-Byte/nft-protocol#260]
https://github.com/Origin-Byte/nft-protocol/blob/main/sources/trading/orderbook.move#L1353

The seller field should be taken from the owner from `Ask`

**Comment by Suficio** [comment]
Thanks for the feedback!

Does https://github.com/Origin-Byte/nft-protocol/pull/247 solve your issue?

**Comment by rm1138** [comment]
> Thanks for the feedback!
> 
> Does #247 solve your issue?

The PR not solved the issue.

**Comment by bausano** [comment]
Fixed in #268

**Comment by bausano** [comment]
Merged to `develop`, in queue for release
