### ISSUE TITLE
Cannot Init Warehouse

### ISSUE THREAD

**Issue by Volthai7us** [Origin-Byte/nft-protocol#301]
I am trying to publish a marketplace. I was following [https://github.com/Origin-Byte/originbyte-js-sdk/tree/main/examples](url)
I am able to create Fee, create Marketplace, create Listing. But when I try to initInventory method. I am getting 

`vmverificationordeserializationerror`.

 Then I tried to call init_warehouse method directly via explorer. Then I encounter with 
 
`Transaction failed with the following error. Error executing transaction with request type: Error: RPC Error: The response returned from RPC server does not match the TypeScript definition. This is likely because the SDK version is not compatible with the RPC server. Please update your SDK version to the latest.`

My initInventory function:
```
import { NftClient } from "@originbyte/js-sdk";
import {
  PACKAGE_OBJECT_ID,
  NFT_MODULE_NAME,
  NFT_CLASS_NAME,
} from "../constants.js";

const initInventory = async (signer) => {
  const transaction = NftClient.buildInitWarehouse({
    packageObjectId: PACKAGE_OBJECT_ID,
    nftModuleName: NFT_MODULE_NAME,
    nftClassName: NFT_CLASS_NAME,
  });
  const initWarehouseResult = await signer.executeMoveCall(transaction);
  console.log(
    "initWarehouseResult",
    JSON.stringify(initWarehouseResult, null, 2)
  );
};

export default initInventory;
```

And these are my constants. 
```
NFT_MODULE_NAME = "suimarines";
NFT_CLASS_NAME = "SUIMARINES";
PACKAGE_OBJECT_ID = "0x5ec4c18d783074abc4ebc71670c521d73b2c7009";
```

And I tried to call init_warehouse on explorer with this type arg:
```
0x5ec4c18d783074abc4ebc71670c521d73b2c7009::suimarines::SUIMARINES
```

Is there a problem with my code or is it about with sui version. What should I do?

**Comment by oribyts** [comment]
Hi @Volthai7us 
Have you deployed the whole `nft-protocol` contract with included submarines or just suimarines? In the 2nd case, there are 2 contracts you are going to interact with: `suimarines` nft collection and `nft-protocol`. Almost all functions have to be called from the `nft-protocol`, but your collection address should be passed as an argument too. For the  `buildInitWarehouse` function, there is a `collectionPackageId` argument, which accepts address of your deployed collection contract, while `packageObjectId` should refer to the current `nft-protocol` instance ([Move.toml:17](https://github.com/Origin-Byte/nft-protocol/blob/main/Move.toml#L17))

**Comment by Volthai7us** [comment]
I always placed `packageObjectId` in my code. But I don't know how to deploy `suimarines`. I didn't see it in example codes. May you send me an example or document.
