### ISSUE TITLE
Local dependency mismatch error.

### ISSUE THREAD

**Issue by vivekascoder** [Origin-Byte/nft-protocol#404]
While publishing my move module that uses `nft-protocol` as a dependency it's causing the following issue.

```
Multiple source verification errors found:

- Local dependency did not match its on-chain version at 0000000000000000000000000000000000000000000000000000000000000002::Sui::transfer_policy
- Local dependency did not match its on-chain version at 0000000000000000000000000000000000000000000000000000000000000002::Sui::kiosk
```

**Comment by ajobi-uhc** [comment]
What version of origin byte are you using

**Comment by vivekascoder** [comment]
MAnage to fix it today.

**Comment by Suficio** [comment]
For anyone encountering this error, it seems that Sui framework is upgraded by republishing at the same address, which breaks any dependents it has.

**Comment by lunajuan** [comment]
> MAnage to fix it today.

how did you fix it?

**Comment by Suficio** [comment]
@lunajuan you can use `--skip-dependency-verification` flag while publishing

**Comment by lunajuan** [comment]
> @lunajuan you can use `--skip-dependency-verification` flag while publishing

Ah, I see! Thank you.
