### ISSUE TITLE
Why we use "TypeName" directly as key, instead of a custom key containing the "TypeName" as key?

### ISSUE THREAD

**Issue by zengxinhai** [Origin-Byte/nft-protocol#424]
https://github.com/Origin-Byte/nft-protocol/blob/fc0950c61837fa599d6aba82fca526d61dee20a2/contracts/allowlist/sources/allowlist/allowlist.move#L222

we could have key like:
```move
struct CollectionTypeKey { type: TypeName } 
```
In this way, we can avoid using the same key with other protocols.

**Comment by bausano** [comment]
I generally use these days 

```move
struct CollectionDfKey<phantom T> {}
```

`DfKey` postfix, phantom type.

In the case of this module, I did not yet have this convention established and the `UID` of the allowlist is not public hence it there's no collision issue.
