### ISSUE TITLE
where the interface?

### ISSUE THREAD

**Issue by letterking** [Origin-Byte/nft-protocol#74]
this so amazing, btw for several people want try this need some upgrade on your work sir, how we can test if UI not show up bro :D

**Comment by nmboavida** [comment]
Hey @letterking thanks for the feedback! Please see our tool [Gutenberg](https://github.com/Origin-Byte/nft-protocol/tree/main/gutenberg) which is a tool that helps you create your own NFT Collection. Currently we are in alpha mode, so to deploy an NFT collection you will have to deploy all the Move modules of our protocol in conjunction. This will change soon, where you will be able to use Gutenberg to just deploy your NFT Collection modules which link up with our on-chain protocol.

Let me know if this helps :D
